# Generated by Django 4.2.1 on 2023-05-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verifed',
            new_name='is_email_verified',
        ),
    ]
