# Generated by Django 4.2.1 on 2023-06-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='image',
        ),
    ]
