# Generated by Django 4.2.1 on 2023-06-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='item',
        ),
    ]
